name: PartyUI
version: 1.0.0
main: PartyUI\Main
api: 5.0.0
author: VsrStudio
commands:
  party:
    description: Open the party menu
    usage: /party
    permission: partyui.command.party
  partyinvite:
    description: Invite a player to your party
    usage: /partyinvite <player>
    permission: partyui.command.partyinvite
  showinvites:
    description: Show your party invites
    usage: /showinvites
    permission: partyui.command.showinvites
permissions:
  partyui.command.party:
    description: Allows the player to open the party menu
    default: true
  partyui.command.partyinvite:
    description: Allows the player to invite other players to their party
    default: true
  partyui.command.showinvites:
    description: Allows the player to see their party invites
    default: true
